# https://VookiImageViewer.cz

image: Visual Studio 2017

version: build{build}

environment:
  matrix:
    - example: VookiImageViewer
      name: win64
      platform: x64
      qt: msvc2017_64

init:
  - set Qt5_DIR=c:\Qt\5.13\%qt%\lib\cmake\Qt5\
  - set QTDIR=c:\Qt\5.13\%qt%
  - set Qt5Core_DIR=%QTDIR%\lib\cmake\Qt5Core\
  - set Qt5Gui_DIR=%QTDIR%\lib\cmake\Qt5Gui\
  - set Qt5Widgets_DIR=%QTDIR%\lib\cmake\Qt5Widgets\
  - set ORIGPATH=%PATH%
  - set PATH=%QTDIR%\bin;;C:\Program Files (x86)\CMake\bin;%PATH%

before_build:
  - qmake -v
  - cmake --version

build_script:
  - cd \projects\vooki-image-viewer\build\cmake\windows
  - generate.bat no-qt-override
  - build-release.bat
  
after_build:
  - cd \projects\vooki-image-viewer\build\cmake\windows
  - deploy-release.bat
  - package.bat

artifacts:
  - path: '**\*.msi'
    name: Testing Installation

test: off

matrix:
  fast_finish: true
