name: MacOS Builds

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: pwd
      run: pwd
    - name: brew
      run: |
        brew update
        brew install qt
        brew link --force qt
    - name: build sources
      run: |
        WORKDIR=`pwd`
        cd ..
        cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild $WORKDIR/build/cmake
        cd build
        make -j install
        ls -l
        cd ..
 #   - name: docker [collect artifacts]
 #     run: |
 #       docker exec macos_docker /bin/sh -c 'cd /root/sources/build/ && tar -cf - *.deb' | tar -xvf -
 #       echo "artifact_name=`ls *.deb`" >> $GITHUB_ENV
  #  - name: archive artifacts
  #    uses: actions/upload-artifact@v3
  #    with:
  #      name: ubuntu_kinetic_${{ env.artifact_name }}
  #      path: |
  #        *.deb
  #      retention-days: 5

