name: Linux Builds

on: workflow_dispatch

jobs:
  ubuntu:
    strategy:
      matrix:
        compiler: [gcc, clang]
        distribution: [jammy, kinetic]
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      docker_image: ghcr.io/vookimedlo/ubuntu-qt:qt6_latestdistroofficial_${{ matrix.compiler }}_${{ matrix.distribution }}
      artifact_name: deb-package_ubuntu_${{ matrix.distribution }}_${{ matrix.compiler }}
  
  debian:
    strategy:
      matrix:
        compiler: [gcc, clang]
        distribution: [stable, bullseye, bookworm]
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      docker_image: ghcr.io/vookimedlo/debian-qt:qt6_latestdistroofficial_${{ matrix.compiler }}_${{ matrix.distribution }}
      artifact_name: deb-package_debian_${{ matrix.distribution }}_${{ matrix.compiler }}

  fedora:
    strategy:
      matrix:
        compiler: [gcc, clang]
        distribution: [stable, 36]
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      docker_image: ghcr.io/vookimedlo/fedora-qt:qt6_latestdistroofficial_${{ matrix.compiler }}_${{ matrix.distribution }}
      artifact_name: rpm-package_fedora_${{ matrix.distribution }}_${{ matrix.compiler }}
